# image will be published to ghcr.io/<user>/<name>
name: ublue-oldair
# description will be included in the image's metadata
description: This is my personal base-OS image for my early Intel MacBook.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/mulderje/facetimehd-kmod/repo/fedora-%OS_VERSION%/mulderje-facetimehd-kmod-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - bash-color-prompt
      - ifuse
      - helix
      - jq
      - just
      - libimobiledevice 
      - libvirt
      - mbpfan
      - neovim
      - p7zip
      - p7zip-plugins
      - podman-compose
      - podman-tui
      - podmansh
      - policycoreutils-python-utils
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-aarch64-core
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - ripgrep
      - setools-console
      - setools-console-analyses
      - setroubleshoot-server
      - tailscale
      - tmux
      - usbmuxd
      - vim
      - virt-install
      - virt-manager
      - virt-viewer
      - wireguard-tools

    remove:
      - firefox
      - firefox-langpacks

    # https://bugzilla.redhat.com/show_bug.cgi?id=2302577
  - type: script
    snippets:
      - "sed -i '0,/enabled=0/{s/enabled=0/enabled=1\npriority=110/}' /etc/yum.repos.d/fedora-updates-testing.repo && curl -LsSf -o wpa_supplicant.rpm https://rpmfind.net/linux/fedora/linux/releases/40/Everything/x86_64/os/Packages/w/wpa_supplicant-2.10-10.fc40.x86_64.rpm && rpm-ostree override replace ./wpa_supplicant.rpm"

  - type: akmods
    base: main
    install:
      - facetimehd
      - wl

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.mozilla.firefox

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans 

  - type: systemd
    system:
      enabled:
        - mbpfan.service
        - podman-auto-update.timer
        - tailscaled.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
