# image will be published to ghcr.io/<user>/<name>
name: ublue-oldair
# description will be included in the image's metadata
description: This is my personal base-OS image for my early Intel MacBook.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - helix
      - jq
      - mbpfan
      - neovim
      - policycoreutils-python-utils
      - ripgrep
      - setools-console
      - setools-console-analyses
      - setroubleshoot-server
      - vim

  - type: script
    scripts:
      - build-kmod-facetimehd.sh
      - build-kmod-wl.sh

  - type: systemd
    system:
      enabled:
        - mbpfan.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
